### ISSUE TITLE
Improve code after the analysis report

### ISSUE THREAD

**Issue by nikopetr** [tk-codes/uno#5]
I've done some code analysis using the CodeMR tool and I've came to the following:

![Untitled](https://user-images.githubusercontent.com/36922092/81558177-e8996a80-9395-11ea-913b-32b7beb6fe51.png)
- The classes NumberCard, ActionCard, WildCard, have Medium-High DIT (Depth of Inheritance Tree) level. This is due to the fact that these classes inherit (extend) the UNOCard class where it itself extends but also implements three more classes.
The high DIT, ie the multiple heredity that takes place from class to class. The deeper the classes inherit other classes, the more difficult it becomes to predict the behavior of these classes. Also, these classes are relatively complex for development, testing and maintenance.

- All directory View classes affect have Medium-High complexity and this is again due to the increased DIT. We can see it clearly in the code as well, as before, there is a deep heredity in these classes.

-  Game class has also medium-high levels and the reason is because if we observe it has relatively more code than other classes and there are also methods within the class that are never called. As a result, WMC (Weighted Method Count) measurement tends to Medium-High. WMC is the sum of all the methods of the class and represents the Cyclomatic complexity of a class, where Cyclomatic complexity is a quantitative measure of independent routes that can be followed by the source code of the program. In addition, the increased number of methods within a class makes these classes tend to change more and be defective. Therefore, it is more obvious that it is not a good choice to have too many methods in a particular class as it will be affected by increased Complexity. 
Notice that if we delete some methods from the class that are not used at all, we directly see the reduction of Complexity from Medium-High to Low-Medium in the class but also in the project in general.

**Comment by tk-codes** [comment]
@nikopetr Thanks a lot for the code analysis report.
I have rebuilt the whole application using domain-driven-design approach.

* `NumberCard`, `ActionCard` and `WildCard` are now immutable value objects in the core domain layer. `CardView` is in the UI presentation layer and receives the card value object in the constructor.
* View classes extends `JPanel`. The problem is `JPanel` itself extends from other class. Since it comes from Java Swing, DIT are hard to fix for our own classes.
* `Game` class is now an aggregate root which consists of players, draw pile and discard pile. In every transaction (play a card, draw a card etc.), it makes sure the state of the entities are changed as whole. Since the aggregate class contains game rule, it actually got bigger now (ca. 300 LoC). Any ideas/suggestions are welcome to reduce the complexity.
